[package]
name = "lachesis"
version = "0.1.0"
authors = ["Michele Federici (@ps1dr3x) <michele@federici.tech>"]
edition = "2018"

[dependencies]
easy_reader = "~0.5.0"
serde = "~1.0"
serde_json = "~1.0"
serde_derive = "~1.0"
regex = "~1.3"
unindent = "~0.1"
semver = "~0.9"
native-tls = "~0.2"
tokio = { version = "~0.2", features = ["macros"] }
tokio-tls = "~0.3"
hyper = "~0.13"
hyper-tls = "~0.4"
indicatif = "~0.13"
rand = "~0.7"
colored = "~1.9"
iprange = "~0.6"
ipnet = "~2.1"
validator = "~0.10"
validator_derive = "~0.10"
rocket = "~0.4"
rocket_contrib = "~0.4"
headless_chrome = "~0.9"
bytes = "~0.5"

[dependencies.clap]
version = "~2.33"
features = ["yaml"]

[dependencies.rusqlite]
version = "~0.21"
features = ["bundled"]
