[package]
name = "lachesis"
version = "0.3.0"
authors = ["Michele Federici (@ps1dr3x) <michele@federici.tech>"]
edition = "2018"

[dependencies]
easy_reader = "=0.5.0"
serde = "=1.0.125"
serde_json = "=1.0.64"
serde_derive = "=1.0.125"
regex = "=1.5.3"
unindent = "=0.1.7"
semver = "=0.11.0"
native-tls = "=0.2.7"
tokio = { version = "=1.5.0", features = ["macros", "rt-multi-thread", "io-util", "net", "sync", "time"] }
tokio-native-tls = "=0.3.0"
hyper = { version = "=0.14.7", features = ["client", "http2"] }
hyper-tls = "=0.5.0"
indicatif = "=0.16.0"
rand = "=0.8.3"
colored = "=2.0.0"
ipnet = "=2.3.0"
validator = "=0.13.0"
validator_derive = "=0.13.0"
rocket = "=0.4.7"
rocket_contrib = "=0.4.7"

[dependencies.clap]
version = "=2.33.3"
features = ["yaml"]

[dependencies.rusqlite]
version = "=0.25.1"
features = ["bundled"]

[dev-dependencies]
hyper = { version = "=0.14.7", features = ["server"] }
