[package]
name = "lachesis"
version = "0.2.0"
authors = ["Michele Federici (@ps1dr3x) <michele@federici.tech>"]
edition = "2018"

[dependencies]
easy_reader = "=0.5.0"
serde = "=1.0.117"
serde_json = "=1.0.59"
serde_derive = "=1.0.117"
regex = "=1.4.1"
unindent = "=0.1.7"
semver = "=0.11.0"
native-tls = "=0.2.4"
futures = "=0.3.6"
tokio = { version = "=0.3.0", features = ["macros", "rt-multi-thread", "io-util", "net", "sync", "time"] }
tokio-tls = "=0.3.1"
hyper = "=0.13.8"
hyper-tls = "=0.4.3"
indicatif = "=0.15.0"
rand = "=0.7.3"
colored = "=2.0.0"
iprange = "=0.6.3"
ipnet = "=2.3.0"
validator = "=0.11.0"
validator_derive = "=0.11.0"
rocket = "=0.4.5"
rocket_contrib = "=0.4.5"
headless_chrome = "=0.9.0"
bytes = "=0.5.6"
num_cpus = "=1.13.0"

[dependencies.clap]
version = "=2.33.3"
features = ["yaml"]

[dependencies.rusqlite]
version = "=0.24.1"
features = ["bundled"]
