[package]
name = "lachesis"
version = "0.2.0"
authors = ["Michele Federici (@ps1dr3x) <michele@federici.tech>"]
edition = "2018"

[dependencies]
easy_reader = "=0.5.0"
serde = "=1.0.110"
serde_json = "=1.0.53"
serde_derive = "=1.0.110"
regex = "=1.3.7"
unindent = "=0.1.5"
semver = "=0.10.0"
native-tls = "=0.2.4"
futures = "=0.3.5"
tokio = { version = "=0.2.21", features = ["macros", "tcp", "rt-threaded", "time"] }
tokio-tls = "=0.3.1"
hyper = "=0.13.5"
hyper-tls = "=0.4.1"
indicatif = "=0.14.0"
rand = "=0.7.3"
colored = "=1.9.3"
iprange = "=0.6.3"
ipnet = "=2.3.0"
validator = "=0.10.0"
validator_derive = "=0.10.0"
rocket = "=0.4.4"
rocket_contrib = "=0.4.4"
headless_chrome = "=0.9.0"
bytes = "=0.5.4"

[dependencies.clap]
version = "=2.33.1"
features = ["yaml"]

[dependencies.rusqlite]
version = "=0.23.1"
features = ["bundled"]
