[package]
name = "lachesis"
version = "0.1.0"
authors = ["Michele Federici (@ps1dr3x) <michele@federici.tech>"]
edition = "2018"

[dependencies]
easy_reader = "=0.3.1"
serde = "=1.0.84"
serde_json = "=1.0.34"
serde_derive = "=1.0.84"
regex = "=1.1.0"
unindent = "=0.1.3"
semver = "=0.9.0"
tokio = "=0.1.11"
hyper = "=0.12.19"
hyper-tls = "=0.3.1"
futures = "=0.1.25"
indicatif = "=0.11"
rand = "=0.6.3"
colored = "=1.6.1"
iprange = "=0.6.2"
ipnet = "=2.0.0"
validator = "=0.8.0"
validator_derive = "=0.8.0"

[dependencies.rusqlite]
version = "=0.16.0"
features = ["bundled"]