[package]
name = "lachesis"
version = "0.1.0"
authors = ["Michele Federici (@ps1dr3x) <michele@federici.tech>"]
edition = "2018"

[dependencies]
easy_reader = "=0.3.1"
serde = "=1.0.90"
serde_json = "=1.0.39"
serde_derive = "=1.0.90"
regex = "=1.1.6"
unindent = "=0.1.3"
semver = "=0.9.0"
tokio = "=0.1.18"
hyper = "=0.12.27"
hyper-tls = "=0.3.2"
futures = "=0.1.26"
indicatif = "=0.11.0"
rand = "=0.6.4"
colored = "=1.7.0"
iprange = "=0.6.2"
ipnet = "=2.0.0"
validator = "=0.8.0"
validator_derive = "=0.8.0"
rocket = "=0.4.0"
rocket_contrib = "=0.4.0"

[dependencies.clap]
version = "=2.33.0"
features = ["yaml"]

[dependencies.rusqlite]
version = "=0.17.0"
features = ["bundled"]
